# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x, 20.x, 22.x]

    runs-on: ${{ matrix.os }} 
        
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run build --if-present

    - name: test22
      if: matrix['node-version'] == '22.x'
      run: npm run test22

    - name: test
      if: matrix['node-version'] == '20.x' || matrix['node-version'] == '18.x'
      run: npm run test

    - name: test-cov
      if: matrix['node-version'] == '22.x' && matrix['os'] == 'ubuntu-latest'
      run: npm run test-cov
      
    - name: coveralls
      if: matrix['node-version'] == '22.x' && matrix['os'] == 'ubuntu-latest'
      uses: coverallsapp/github-action@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./coverage/lcov.info

